// HLYST DJ roster — all 15 DJs, complete real content transcribed from the
// actual HLYST poster designs. No placeholders remain.
//
// Place this file at: web/lib/djs.ts (REPLACES the existing version entirely)

export interface DjProfile {
  slug: string;
  name: string;
  onAirName: string;
  title: string;
  schedule: string;
  portrait: string;
  about: string;
  inHisLane: string;
  onAirStyle: string;
  theVibe: string;
  theAudience: string;
  whatHeBrings: string;
  trustedFor: string;
  signatureQuote: string;
}

export const djs: DjProfile[] = [
  {
    slug: 'vanessa-king',
    name: 'Vanessa King',
    onAirName: 'Vanessa King',
    title: 'The Weekend Editor',
    schedule: 'Weekend DJ · Saturdays 10AM–2PM, Sundays 6PM–10PM',
    portrait: '/Vanessa King.png',
    about: "Vanessa King curates the perfect soundtrack for your weekend. She's the editor—blending the classics, the current, and the culture. Every set is intentional. Every transition is smooth. Every vibe is exactly what the weekend needs. From feel-good mornings to laid-back afternoons to unforgettable nights, Vanessa sets the tone and keeps it HLYST. She doesn't follow the playlist—she edits the experience. The right music. The right time. Every time. That's Vanessa King.",
    inHisLane: 'R&B / Neo-Soul / House / Old School / Hip-Hop / Weekend Favorites',
    onAirStyle: 'Warm. Smooth. Conversational. Intentional. Effortless flow.',
    theVibe: 'Feel-Good. Soulful. Chill. Uplifting. Weekend energy.',
    theAudience: 'Everyone. All ages. Good people. Culture lovers.',
    whatHeBrings: 'The right music. The right mood. The right timing. The right energy.',
    trustedFor: 'The right music. The right transitions. The right moments. The right vibe.',
    signatureQuote: "I don't just play music. I edit moments. I curate vibes. I make your weekend sound better. This is HLYST.",
  },
  {
    slug: 'bellamy-tha-blueprint',
    name: 'Bellamy',
    onAirName: 'Bellamy tha Blueprint',
    title: 'The Architect of the Vibe',
    schedule: 'Weekend DJ · Saturdays 6PM–10PM',
    portrait: '/Bellamy Tha Blueprint.png',
    about: "Bellamy doesn't follow the wave—he builds the current. He's the planner, the curator, the vibe architect. Every record has a place. Every transition has purpose. He creates Saturday nights that feel like a set, not a shuffle.",
    inHisLane: 'R&B / Neo-Soul / Contemporary Soul / Sophisticated Groove',
    onAirStyle: 'Smooth. Intentional. Knowledgeable. Atmosphere builder.',
    theVibe: 'Sophisticated. Mature. Grown. Always on point.',
    theAudience: 'Grown & cultured. Not just listeners—true appreciators.',
    whatHeBrings: 'Blueprint sets. Deep cuts. Timeless energy.',
    trustedFor: 'The right records. The right moments. The right feel.',
    signatureQuote: 'Bellamy tha Blueprint. Builds the nights you remember.',
  },
  {
    slug: 'winslow-the-cypher',
    name: 'Winslow',
    onAirName: 'Winslow the Cypher',
    title: 'The Cypher',
    schedule: 'Weekend DJ · Saturdays 10AM–2PM',
    portrait: '/Winslow_ The Cypher.png',
    about: 'Winslow lives where hip hop began—in the block, in the booth, and in the bars. He honors the roots while pushing the culture forward. Expect real talk, tight mixes, and the soundtrack to a movement.',
    inHisLane: 'Hip Hop / Boom Bap / Conscious Rap / Neo-Soul / Spoken Word',
    onAirStyle: 'Raw. Intelligent. Unfiltered. Always authentic.',
    theVibe: 'High energy. Deep content. Culture forward.',
    theAudience: 'The thinkers. The creators. The truth seekers.',
    whatHeBrings: 'Real bars. Real conversations. Real connection.',
    trustedFor: 'The right lyrics. The right energy. The right message.',
    signatureQuote: "It's more than a show. It's a state of mind. Welcome to the cypher.",
  },
  {
    slug: 'uncle-ray',
    name: 'Uncle Ray',
    onAirName: 'Uncle Ray',
    title: 'The Foundation',
    schedule: 'Weekend DJ · Saturdays 2PM–6PM',
    portrait: '/Uncle Ray.png',
    about: "Uncle Ray is the heartbeat of the culture. He keeps it classic, keeps it real, and keeps the history alive. From the soul of the streets to the soundtracks of our lives—he connects generations. Knowledge. Experience. Respect. That's Uncle Ray.",
    inHisLane: 'Classic Hip Hop / R&B Classics / Old School Soul / Real Talk',
    onAirStyle: 'Knowledgeable. Laid-back. Real & Respectful. Always Authentic.',
    theVibe: 'Nostalgic. Timeless. Grounded. Grown & Real.',
    theAudience: 'Mature Listeners. Loyal Listeners. Culture Lovers. Students of the Game.',
    whatHeBrings: 'The lessons. The classics. The culture. The connection.',
    trustedFor: 'The right records. The right stories. The right perspective. The right time.',
    signatureQuote: "I play the records. I tell the stories. I pass the knowledge. That's how we keep it alive.",
  },
  {
    slug: 'lady-t',
    name: 'Lady T',
    onAirName: 'Lady T',
    title: 'The Vibe Controller',
    schedule: 'Weekend DJ · Fridays 7PM–11PM',
    portrait: '/Lady T.png',
    about: "Lady T brings experience, intuition, and energy. She controls the vibe and connects the culture. From timeless classics to today's hits, she blends it all with purpose. Smooth. Confident. Unmistakable. You don't just hear Lady T—you feel her in the mix.",
    inHisLane: 'R&B / Neo-Soul / Classic Hip Hop / Throwbacks / Party Starters',
    onAirStyle: 'Smooth. Confident. Engaging. Seamless transitions. Crowd reader.',
    theVibe: 'Feel good. High energy. Timeless. Always right.',
    theAudience: 'Grown & cultured. Loyal listeners. Vibe chasers. Music lovers.',
    whatHeBrings: 'Years of experience. Perfect timing. Real connection. The right energy.',
    trustedFor: 'The right mix. The right moments. The right energy. The right vibe.',
    signatureQuote: "I don't just play music. I control the vibe. I connect the culture. I am Lady T.",
  },
  {
    slug: 'eric-jordan',
    name: 'Eric Jordan',
    onAirName: 'Eric Jordan',
    title: 'The Connector',
    schedule: 'Weekend DJ · Saturdays 6PM–10PM',
    portrait: '/Eric Jordan.png',
    about: "Eric Jordan connects the dots. From classic to current, R&B to Hip Hop, and everything in between—he makes sure the music flows and the culture stays in the mix. A student of the game. A curator of the moment. A connector of people and sound. That's Eric Jordan.",
    inHisLane: "R&B / Hip Hop / Soul Classics / Classic Throwbacks / Today's Hits",
    onAirStyle: 'Smooth. Knowledgeable. Engaging. Great transitions. Always on point.',
    theVibe: 'Timeless. Connected. Real energy. All generations.',
    theAudience: 'Loyal listeners. Culture lovers. Music heads. All ages. All vibes.',
    whatHeBrings: 'The right music. The right mood. The right connection. The right time.',
    trustedFor: 'The right blends. The right records. The right moments. The right energy.',
    signatureQuote: 'I connect the music. I connect the culture. I connect the people. I am Eric Jordan.',
  },
  {
    slug: 'nicole-james',
    name: 'Nicole James',
    onAirName: 'Nicole James',
    title: 'The Night Shift',
    schedule: 'Weekend DJ · Fridays 10PM–2AM',
    portrait: '/Nicole Jame.png',
    about: "When the sun goes down, Nicole James takes over. The Night Shift is where grown folks come to vibe, unwind, and get it right. Smooth mixes. Real energy. R&B. Soul. Slow Jams. Classics. She sets the tone and keeps the night right. It's not just a shift—it's her time. That's Nicole James.",
    inHisLane: 'R&B / Soul / Slow Jams / Classic Hits / Grown & Sexy',
    onAirStyle: 'Smooth. Sultry. Confident. Engaging. Real talk. Always in control.',
    theVibe: 'Late nights. Good vibes. Deep feels. Timeless sounds.',
    theAudience: 'Grown & cultured. Loyal listeners. Night owls. Vibe seekers.',
    whatHeBrings: 'Great music. Great timing. Great energy. A night to remember.',
    trustedFor: 'The right vibe. The right mix. The right energy. The right night.',
    signatureQuote: "I don't just play music. I set the tone for your night. I bring the vibes. I am Nicole James.",
  },
  {
    slug: 'aaron-price',
    name: 'Aaron Price',
    onAirName: 'Aaron Price',
    title: 'The Archivist',
    schedule: 'Weekend DJ · Sundays 6AM–10AM',
    portrait: '/Aaron Price.png',
    about: "Aaron Price preserves the past so the culture stays connected to its roots. He digs deep, he's detailed, and he delivers the records that built the movement. Old soul. Sharp mind. Deep crate. A keeper of the legacy. The music. The stories. The truth. If it matters to the culture, Aaron Price has it.",
    inHisLane: 'Classic Hip-Hop / Golden Era / Soul Samples / Rare Gems / Story Behind the Song',
    onAirStyle: 'Informative. Thoughtful. Respectful. Always on point.',
    theVibe: 'Nostalgic. Thought-provoking. Deeply rooted. Timeless.',
    theAudience: 'The real ones. Culture historians. Heads. Multi-generational.',
    whatHeBrings: 'The rare records. The real stories. The deep cuts. The missing pieces.',
    trustedFor: 'The right records. The right context. The right history. The right time.',
    signatureQuote: 'Every record has a story. Every story has a purpose. Every purpose keeps the culture alive. This is HLYST.',
  },
  {
    slug: 'marcus-reed',
    name: 'Marcus Reed',
    onAirName: 'Marcus Reed',
    title: 'The Culture Curator',
    schedule: 'Weekend DJ · Saturdays 10PM–2AM',
    portrait: '/Marcus Reed.png',
    about: "Marcus Reed connects the dots between generations and genres. He knows the classics, lives the now, and champions what's next. A student of the culture. A voice for the streets. A curator of real music for real people. This is more than a set—this is the culture, curated.",
    inHisLane: 'Hip-Hop / R&B / Throwbacks / New Heat / Underground Gems',
    onAirStyle: 'Confident. Charismatic. Engaging. Unfiltered. Made for the culture.',
    theVibe: 'High Energy. Real Connections. Culture forward. Always authentic.',
    theAudience: 'The culture. The community. The real ones. The next wave.',
    whatHeBrings: 'The right records. The right energy. The right message. The right now.',
    trustedFor: 'The right records. The right moments. The right voice. The right impact.',
    signatureQuote: "I don't just play music. I curate moments that matter. This is our culture. This is HLYST.",
  },
  {
    slug: 'julian-cross',
    name: 'Julian Cross',
    onAirName: 'Julian Cross',
    title: 'The Night Architect',
    schedule: 'Weekend DJ · Fridays 2AM–6AM',
    portrait: '/Julian Cross.png',
    about: "Julian Cross designs the soundtrack to your late-night hours. He blends deep cuts, future classics, and timeless grooves into a seamless journey that keeps you locked in 'til sunrise. Every mix is deliberate. Every transition is flawless. Every night is an experience. That's Julian Cross.",
    inHisLane: 'Neo-Soul / Late Night Grooves / Deep Cuts / Future Classics',
    onAirStyle: 'Smooth. Detailed. Intentional. Unrushed. Master of the mood.',
    theVibe: 'Late. Atmospheric. Immersive. Sophisticated. Built for the night.',
    theAudience: 'Night listeners. Deep listeners. Culture lovers. True music heads.',
    whatHeBrings: 'The deep records. The perfect blend. The late-night energy. The mood you remember.',
    trustedFor: 'The right records. The right timing. The right transitions. The right night.',
    signatureQuote: "When the world gets quiet, the music gets deeper. That's when I build. This is HLYST.",
  },
  {
    slug: 'miss-renee-cole',
    name: 'Miss Renee Cole',
    onAirName: 'Miss Renee Cole',
    title: 'The Evening Experience',
    schedule: 'Weekend DJ · Saturdays 8PM–12AM',
    portrait: '/Miss Renee Cole.png',
    about: "Miss Renee Cole brings elegance, depth, and soul to your Saturday night. She blends timeless classics with today's favorites and delivers the kind of show that feels like a conversation with your best friend. Smart. Warm. Authentic. Miss Renee doesn't just play records—she creates moments.",
    inHisLane: 'R&B / Soul / Quiet Storm / Neo-Soul / Timeless Classics',
    onAirStyle: 'Smooth. Warm. Intelligent. Engaging. Effortlessly real.',
    theVibe: 'Relaxed. Soulful. Uplifting. Feel-good energy.',
    theAudience: 'Mature & loyal. Soulful & selective. Quality listeners. Culture lovers.',
    whatHeBrings: 'The soundtrack. The mood. The connection. The feel you remember.',
    trustedFor: 'The right song. The right moment. The right words. The right feel.',
    signatureQuote: "Good music. Good company. Good conversation. That's my Saturday night. This is HLYST.",
  },
  {
    slug: 'miles-grant',
    name: 'Miles Grant',
    onAirName: 'Miles Grant',
    title: 'The Weekend Journeyman',
    schedule: 'Weekend DJ · Saturdays 2PM–6PM, Sundays 2PM–6PM',
    portrait: '/Miles Grant.png',
    about: "Miles Grant is built for the weekend. He's the link between your work week and your peace of mind. He blends generations, styles, and sounds into one smooth experience. No gimmicks. No rush. Just good music, good energy, and good vibes. Miles Grant makes the weekend feel like home.",
    inHisLane: 'Hip-Hop / R&B / House / Reggae / Soul / Party Anthems / Timeless Favorites',
    onAirStyle: 'Smooth. Laid-Back. Engaging. Genuine. Effortless flow.',
    theVibe: 'Upbeat. Feel-Good. Weekend energy. Wide appeal. Feel like freedom.',
    theAudience: 'Everyone. All ages. Good people. Weekend ready.',
    whatHeBrings: 'The right mix. The right timing. The right energy. The right vibe.',
    trustedFor: 'The right music. The right transitions. The right moments. The right time.',
    signatureQuote: "Weekends aren't just days. They're a state of mind. I bring the soundtrack. You live the moment. This is HLYST.",
  },
  {
    slug: 'monica-hayes',
    name: 'Monica Hayes',
    onAirName: 'Monica Hayes',
    title: 'The Balance Keeper',
    schedule: 'Weekend DJ · Saturdays 6PM–10PM, Sundays 12PM–4PM',
    portrait: '/Monica Hayes.png',
    about: "Monica Hayes creates space for every mood and every moment. She blends feel-good favorites, timeless classics, and today's hits into the perfect vibe. Smooth transitions. Positive energy. Great music. Good company. She keeps it balanced, keeps it moving, and keeps it HLYST. Saturday nights. Sunday afternoons. Monica has you.",
    inHisLane: "R&B / Neo-Soul / Classic Hits / Feel-Good Favorites / Today's Hits",
    onAirStyle: 'Warm. Welcoming. Engaging. Relatable. Effortless flow.',
    theVibe: 'Feel-Good. Uplifting. Relaxed & Fun. Good Energy.',
    theAudience: 'Everyone. All ages. All walks of life. Loyal listeners.',
    whatHeBrings: 'The right mix. The right mood. The right energy. The right experience.',
    trustedFor: 'The right music. The right transitions. The right vibe. The right company.',
    signatureQuote: "Good music. Good people. Good vibes. That's the balance. That's HLYST.",
  },
  {
    slug: 'simone-ellis',
    name: 'Simone Ellis',
    onAirName: 'Simone Ellis',
    title: 'The Feel Good Maven',
    schedule: 'Weekend DJ · Saturdays 12PM–4PM, Sundays 4PM–8PM',
    portrait: '/Simone Ellis.png',
    about: "Simone Ellis is all about feel-good energy and real connection. She brings the perfect blend of classics, current favorites, and today's hits to keep your weekend on point. Smooth mixes. Uplifting vibes. Positive conversations. Great company. She sets the tone for your Saturday and Sunday and keeps it HLYST. It's more than music—it's a vibe. It's Simone Ellis.",
    inHisLane: 'R&B / Neo-Soul / Pop / Classic Hits / Feel-Good Favorites / Weekend Anthems',
    onAirStyle: 'Warm. Inviting. Engaging. Uplifting. Always authentic.',
    theVibe: 'Feel-Good. Upbeat. Positive. High Energy.',
    theAudience: 'Everyone. All ages. Good people. Vibe seekers.',
    whatHeBrings: 'The right music. The right vibe. The right energy. The right connection.',
    trustedFor: 'The right music. The right moments. The right conversations. The right vibe.',
    signatureQuote: 'Music is the soundtrack to our lives. I just make sure it feels good. This is HLYST.',
  },
  {
    slug: 'terri-mitchell',
    name: 'Terri Mitchell',
    onAirName: 'Terri Mitchell',
    title: 'The Moment Maker',
    schedule: 'Weekend DJ · Saturdays 4PM–8PM, Sundays 10AM–2PM',
    portrait: '/Terri Mitchell.png',
    about: "Terri Mitchell lives for the moments that matter. She turns up the good times and brings people together through music. From timeless classics to today's favorites, she creates a feel-good experience that sticks with you. Smooth blends. Big energy. Positive vibes. Real connection. Terri doesn't just play the soundtrack—she makes the moment. Every Saturday afternoon. Every Sunday late morning. Terri Mitchell makes it HLYST.",
    inHisLane: 'R&B / Neo-Soul / Classic Hits / Feel-Good Favorites / Sunday Brunch Vibes',
    onAirStyle: 'Warm. Genuine. Engaging. Uplifting. Flows with ease.',
    theVibe: 'Feel-Good. Upbeat. Positive. Connected.',
    theAudience: 'Everyone. All ages. Good people. Community driven.',
    whatHeBrings: 'The right mix. The right energy. The right moments. The right feeling.',
    trustedFor: 'The right music. The right vibe. The right transitions. The right experience.',
    signatureQuote: 'Life is made of moments. I just add the music that makes them unforgettable. This is HLYST.',
  },
];

export function getDjBySlug(slug: string): DjProfile | undefined {
  return djs.find(d => d.slug === slug);
}
